# Generated by Django 3.1.4 on 2021-01-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0002_auto_20210106_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank='true', null='true', on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile'),
            preserve_default='true',
        ),
    ]
